{% set version = "1.4.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-loon
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/loon_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/loon/loon_{{ version }}.tar.gz
  sha256: 57a11bef450299e1cd5551c114e49c361ad05b82483f0198bc7935870e3ceb0c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-gridextra
  run:
    - r-base
    - r-gridextra

test:
  commands:
    - $R -e "library('loon')"                 # [not (win or linux)]
    - xvfb-run -a -- $R -e "library('loon')"  # [linux]
    - "\"%R%\" -e \"library('loon')\""        # [win]

about:
  home: https://great-northern-diver.github.io/loon/
  license: GPL-2.0-only
  summary: An extendable toolkit for interactive data visualization and exploration.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
